"""add auth_user table

Revision ID: b0bd8491f6b3
Revises: 64ec9a0a8787
Create Date: 2024-04-28 20:15:08.197167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0bd8491f6b3'
down_revision: Union[str, None] = '64ec9a0a8787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
